<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.3 (Python 3.10.1 on win32)" generated="20220124 13:16:58.843" rpa="true" schemaversion="2">
<suite id="s1" name="Tmp" source="C:\rpa\tmp.robot">
<test id="s1-t1" name="Login as user">
<kw name="Open available Browser">
<arg>https://example.com</arg>
<msg timestamp="20220124 13:16:58.897" level="FAIL">No keyword with name 'Open available Browser' found.</msg>
<status status="FAIL" starttime="20220124 13:16:58.897" endtime="20220124 13:16:58.897"/>
</kw>
<status status="FAIL" starttime="20220124 13:16:58.895" endtime="20220124 13:16:58.898">No keyword with name 'Open available Browser' found.</status>
</test>
<status status="FAIL" starttime="20220124 13:16:58.847" endtime="20220124 13:16:58.899"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tasks</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Tmp">Tmp</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220124 13:16:58.891" level="ERROR">Error in file 'C:\rpa\tmp.robot' on line 2: Importing library 'RPA.Browser.Selenium' failed: ModuleNotFoundError: No module named 'RPA'
Traceback (most recent call last):
  None
PYTHONPATH:
  .
  C:\rpa\.rpa\Scripts\uvicorn.exe
  C:\Users\adly\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\adly\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\adly\AppData\Local\Programs\Python\Python310\lib
  C:\Users\adly\AppData\Local\Programs\Python\Python310
  C:\rpa\.rpa
  C:\rpa\.rpa\lib\site-packages</msg>
</errors>
</robot>
